# Generated by Django 5.1.2 on 2024-10-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_analysisresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialdata',
            name='profit',
        ),
        migrations.AddField(
            model_name='financialdata',
            name='cash_inflow',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='financialdata',
            name='cash_outflow',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='financialdata',
            name='net_cash_flow',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
