# Generated by Django 5.1.2 on 2024-10-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_financialdata_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdata',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
