# Generated by Django 5.1.2 on 2024-10-19 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_cashflow_category_financialinsight_financialreport_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CashFlow',
        ),
    ]
